"""
Audit event schemas (Pydantic v2).

What is an audit event?
-----------------------
An audit event is an **append-only log entry** describing something that happened in the system:
- an issue was created
- an agent run completed
- a human recorded a decision
- a document was ingested (future RAG)

Why this matters in pharma/biotech
----------------------------------
In regulated environments, you often need to show a clear timeline:
"What happened, when, and who/what did it?"

An audit trail helps with:
- internal governance and QC
- inspection readiness (the "why" and "when" are not lost)
- debugging and accountability

Important design idea
---------------------
Audit logs are typically **append-only**. You don't edit old events; you add new events.
That makes the timeline trustworthy.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class AuditEventType(str, Enum):
    """
    Standard categories for audit events.

    You can add more over time as the product grows.
    Using an Enum prevents inconsistent naming like "issueCreated" vs "issue_created".
    """

    ISSUE_CREATED = "ISSUE_CREATED"
    ISSUE_UPDATED = "ISSUE_UPDATED"
    ANALYZE_RUN_CREATED = "ANALYZE_RUN_CREATED"
    DECISION_RECORDED = "DECISION_RECORDED"
    DOCUMENT_INGESTED = "DOCUMENT_INGESTED"


class AuditEvent(BaseModel):
    """
    A single audit log entry.

    Minimal required fields (aligned to the API spec):
    - `event_id`: unique ID for this audit event
    - `event_type`: what happened (category)
    - `created_at`: when it happened (UTC)
    - `actor`: who/what did it (username or service name)

    Optional linkage fields:
    - `issue_id`, `run_id`, `decision_id` allow tying events back to objects.

    `details` is structured JSON for additional context (small and safe to store).
    """

    event_id: UUID = Field(
        default_factory=uuid4,
        description="Unique identifier for the audit event (generated by the system).",
    )
    event_type: AuditEventType = Field(..., description="Category describing what happened.")

    # Use UTC for consistency across systems and teams.
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when the event was created.",
    )

    actor: str = Field(
        ...,
        description="Identifier for the actor (e.g., username for human, service name for system).",
    )

    # These IDs are optional because some events may not relate to a specific object.
    issue_id: UUID | None = Field(
        default=None,
        description="Optional issue ID associated with the event.",
    )
    run_id: UUID | None = Field(
        default=None,
        description="Optional agent run ID associated with the event.",
    )
    # We keep details as structured JSON, so the API can return "what was recorded"
    # without needing free-form message parsing.
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional structured details (avoid large payloads; keep it small and audit-friendly).",
    )

