"""
Agent run schemas (Pydantic v2).

An "agent run" represents one execution of the triage workflow for a specific issue.
In production, this is the record you would store for auditability and replay:
when it ran, what versions were used, and what recommendation it produced.
"""

from datetime import datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from agent.schemas.recommendation import Action, AgentRecommendation, Severity


class AgentRun(BaseModel):
    """
    Full record of a single agent run for a given issue.

    Notes:
    - `run_id` is generated by the system (UUID).
    - `created_at` uses UTC time (simple baseline).
    - `rules_version` is included so outputs can be traced back to the rule set used.
    """

    run_id: UUID = Field(
        default_factory=uuid4,
        description="Unique identifier for this agent run (generated by the system).",
    )
    issue_id: UUID = Field(..., description="The issue this run is associated with.")
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when the run was created.",
    )
    rules_version: str = Field(
        default="v0.1",
        description="Version of deterministic rules used for this run.",
    )
    recommendation: AgentRecommendation = Field(
        ...,
        description="The agent’s structured recommendation output for the issue.",
    )


class AgentRunSummary(BaseModel):
    """
    Lightweight summary for list views.

    This intentionally duplicates a few fields from the recommendation so list endpoints
    can return a compact summary without returning the full nested recommendation payload.
    """

    run_id: UUID = Field(..., description="Unique identifier for this agent run.")
    created_at: datetime = Field(..., description="UTC timestamp when the run was created.")
    severity: Severity = Field(..., description="Severity from the recommendation.")
    action: Action = Field(..., description="Action from the recommendation.")
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0 and 1 (inclusive).",
    )

    @classmethod
    def from_run(cls, run: AgentRun) -> "AgentRunSummary":
        """Create a summary from a full `AgentRun`."""

        return cls(
            run_id=run.run_id,
            created_at=run.created_at,
            severity=run.recommendation.severity,
            action=run.recommendation.action,
            confidence=run.recommendation.confidence,
        )
